package de.hsrm.mi.swt.rheinmainadventure.messaging;

public enum NachrichtenCode {
    NEUER_MITSPIELER, MITSPIELER_VERLÄSST, LOBBYZEIT_ABGELAUFEN, BEITRETEN_FEHLGESCHLAGEN, SCHON_BEIGETRETEN,
    LOBBY_GESTARTET, LOBBY_VOLL, COUNTDOWN_GESTARTET, KEINE_LOBBY_FREI;
}
